name: Test Branch
on:
  pull_request:
  push:

permissions:
  pull-requests: write
  contents: write

jobs:
  test-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Pytest coverage comment
        id: coverageComment
        uses: ./
        with:
          pytest-xml-coverage-path: ./data/coverage_1.xml
          # pytest-coverage-path: ./data/pytest-coverage_4.txt
          junitxml-path: ./data/pytest_1.xml

      - name: Check the output coverage
        run: |
          echo "Coverage Report - ${{ steps.coverageComment.outputs.coverage }}"
          echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
          echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}"
